name: video_player_app
publish_to: 'none'

version: 1.0.2
description: "A new Flutter project."

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.9.1
  chewie: ^1.8.3
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/videos/HRCodeExperts.mp4